[phases.setup]
nixPkgs = ["python311", "pkg-config", "cairo", "pango", "gdk-pixbuf", "libffi", "shared-mime-info"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py migrate --noinput",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn college_backend.wsgi:application --bind 0.0.0.0:$PORT"



